name = "hetkijkpunt"
main = "worker/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "hetkijkpunt.nl", custom_domain = true },
  { pattern = "www.hetkijkpunt.nl", custom_domain = true },
]

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "force-trailing-slash"
not_found_handling = "404-page"
run_worker_first = ["/sitemap*.xml", "/sitemap.xml"]
